package resources

import (
	"testing"

	resourcesv1 "github.com/dragonflydb/dragonfly-operator/api/v1alpha1"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	corev1 "k8s.io/api/core/v1"
	networkingv1 "k8s.io/api/networking/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/util/intstr"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

func TestMergeNamedSlices_Containers(t *testing.T) {
	base := []corev1.Container{
		{Name: "main", Image: "main:1"},
		{Name: "sidecar", Image: "sidecar:1"},
	}
	override := []corev1.Container{
		{Name: "main", Image: "main:custom"},
		{Name: "metrics", Image: "metrics:1"},
	}

	result := mergeNamedSlices(base, override, func(c corev1.Container) string { return c.Name })

	assert.Len(t, result, 3)
	assert.Equal(t, "main:custom", result[0].Image)
	assert.Equal(t, "metrics:1", result[1].Image)
	assert.Equal(t, "sidecar:1", result[2].Image)
}

func TestMergeNamedSlices_Volumes(t *testing.T) {
	base := []corev1.Volume{
		{Name: "config"},
		{Name: "data"},
	}
	override := []corev1.Volume{
		{Name: "config"}, // override
		{Name: "logs"},
	}

	result := mergeNamedSlices(base, override, func(v corev1.Volume) string { return v.Name })

	assert.Len(t, result, 3)
	assert.Equal(t, "config", result[0].Name)
	assert.Equal(t, "logs", result[1].Name)
	assert.Equal(t, "data", result[2].Name)
}

func TestMergeNamedSlices_EmptyOverride(t *testing.T) {
	base := []corev1.Volume{
		{Name: "default"},
	}
	override := []corev1.Volume{}

	result := mergeNamedSlices(base, override, func(v corev1.Volume) string { return v.Name })

	assert.Len(t, result, 1)
	assert.Equal(t, "default", result[0].Name)
}

func TestMergeNamedSlices_EmptyBase(t *testing.T) {
	base := []corev1.Container{}
	override := []corev1.Container{
		{Name: "user", Image: "user:1"},
	}

	result := mergeNamedSlices(base, override, func(c corev1.Container) string { return c.Name })

	assert.Len(t, result, 1)
	assert.Equal(t, "user", result[0].Name)
}

func findNetworkPolicy(objs []client.Object) *networkingv1.NetworkPolicy {
	for _, obj := range objs {
		if np, ok := obj.(*networkingv1.NetworkPolicy); ok {
			return np
		}
	}
	return nil
}

func TestGenerateDragonflyResources_NetworkPolicyDefault(t *testing.T) {
	df := &resourcesv1.Dragonfly{
		ObjectMeta: metav1.ObjectMeta{
			Name:      "test-df",
			Namespace: "default",
		},
		Spec: resourcesv1.DragonflySpec{
			Replicas: 1,
		},
	}

	objs, err := GenerateDragonflyResources(df, "")
	require.NoError(t, err)

	np := findNetworkPolicy(objs)
	require.NotNil(t, np, "NetworkPolicy should be generated by default")

	assert.Equal(t, "test-df", np.Name)
	assert.Equal(t, "default", np.Namespace)

	assert.Equal(t, map[string]string{
		DragonflyNameLabelKey:     "test-df",
		KubernetesPartOfLabelKey:  KubernetesPartOf,
		KubernetesAppNameLabelKey: KubernetesAppName,
	}, np.Spec.PodSelector.MatchLabels)

	require.Len(t, np.Spec.Ingress, 2)
	assert.Equal(t, []networkingv1.PolicyType{networkingv1.PolicyTypeIngress}, np.Spec.PolicyTypes)

	protocolTCP := corev1.ProtocolTCP

	clientRule := np.Spec.Ingress[0]
	assert.Len(t, clientRule.From, 0, "client port should be open to all")
	require.Len(t, clientRule.Ports, 1)
	assert.Equal(t, &protocolTCP, clientRule.Ports[0].Protocol)
	assert.Equal(t, intstr.FromInt32(DragonflyPort), *clientRule.Ports[0].Port)

	adminRule := np.Spec.Ingress[1]
	require.Len(t, adminRule.Ports, 1)
	assert.Equal(t, intstr.FromInt32(DragonflyAdminPort), *adminRule.Ports[0].Port)
	require.Len(t, adminRule.From, 2)

	operatorPeer := adminRule.From[0]
	assert.Equal(t, map[string]string{
		OperatorControlPlaneLabelKey: OperatorControlPlaneLabelValue,
	}, operatorPeer.PodSelector.MatchLabels)
	assert.NotNil(t, operatorPeer.NamespaceSelector, "operator peer should allow cross-namespace")

	peerPod := adminRule.From[1]
	assert.Equal(t, map[string]string{
		DragonflyNameLabelKey:     "test-df",
		KubernetesPartOfLabelKey:  KubernetesPartOf,
		KubernetesAppNameLabelKey: KubernetesAppName,
	}, peerPod.PodSelector.MatchLabels)
	assert.Nil(t, peerPod.NamespaceSelector, "peer pod should be same-namespace only")
}

func TestGenerateDragonflyResources_NetworkPolicyDisabled(t *testing.T) {
	disabled := false
	df := &resourcesv1.Dragonfly{
		ObjectMeta: metav1.ObjectMeta{
			Name:      "test-df",
			Namespace: "default",
		},
		Spec: resourcesv1.DragonflySpec{
			Replicas:             1,
			NetworkPolicyEnabled: &disabled,
		},
	}

	objs, err := GenerateDragonflyResources(df, "")
	require.NoError(t, err)

	np := findNetworkPolicy(objs)
	assert.Nil(t, np, "NetworkPolicy should not be generated when disabled")
}

func TestGenerateDragonflyResources_NetworkPolicyWithMemcached(t *testing.T) {
	df := &resourcesv1.Dragonfly{
		ObjectMeta: metav1.ObjectMeta{
			Name:      "test-df",
			Namespace: "default",
		},
		Spec: resourcesv1.DragonflySpec{
			Replicas:      1,
			MemcachedPort: 11211,
		},
	}

	objs, err := GenerateDragonflyResources(df, "")
	require.NoError(t, err)

	np := findNetworkPolicy(objs)
	require.NotNil(t, np)

	require.Len(t, np.Spec.Ingress, 3, "should have client, admin, and memcached rules")

	protocolTCP := corev1.ProtocolTCP
	memcachedRule := np.Spec.Ingress[2]
	assert.Len(t, memcachedRule.From, 0, "memcached port should be open to all")
	require.Len(t, memcachedRule.Ports, 1)
	assert.Equal(t, &protocolTCP, memcachedRule.Ports[0].Protocol)
	assert.Equal(t, intstr.FromInt32(11211), *memcachedRule.Ports[0].Port)
}
