package resources

import (
	"testing"

	resourcesv1 "github.com/dragonflydb/dragonfly-operator/api/v1alpha1"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	networkingv1 "k8s.io/api/networking/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/apimachinery/pkg/util/intstr"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

func TestMergeNamedSlices_Containers(t *testing.T) {
	base := []corev1.Container{
		{Name: "main", Image: "main:1"},
		{Name: "sidecar", Image: "sidecar:1"},
	}
	override := []corev1.Container{
		{Name: "main", Image: "main:custom"},
		{Name: "metrics", Image: "metrics:1"},
	}

	result := mergeNamedSlices(base, override, func(c corev1.Container) string { return c.Name })

	assert.Len(t, result, 3)
	assert.Equal(t, "main:custom", result[0].Image)
	assert.Equal(t, "metrics:1", result[1].Image)
	assert.Equal(t, "sidecar:1", result[2].Image)
}

func TestMergeNamedSlices_Volumes(t *testing.T) {
	base := []corev1.Volume{
		{Name: "config"},
		{Name: "data"},
	}
	override := []corev1.Volume{
		{Name: "config"}, // override
		{Name: "logs"},
	}

	result := mergeNamedSlices(base, override, func(v corev1.Volume) string { return v.Name })

	assert.Len(t, result, 3)
	assert.Equal(t, "config", result[0].Name)
	assert.Equal(t, "logs", result[1].Name)
	assert.Equal(t, "data", result[2].Name)
}

func TestMergeNamedSlices_EmptyOverride(t *testing.T) {
	base := []corev1.Volume{
		{Name: "default"},
	}
	override := []corev1.Volume{}

	result := mergeNamedSlices(base, override, func(v corev1.Volume) string { return v.Name })

	assert.Len(t, result, 1)
	assert.Equal(t, "default", result[0].Name)
}

func TestMergeNamedSlices_EmptyBase(t *testing.T) {
	base := []corev1.Container{}
	override := []corev1.Container{
		{Name: "user", Image: "user:1"},
	}

	result := mergeNamedSlices(base, override, func(c corev1.Container) string { return c.Name })

	assert.Len(t, result, 1)
	assert.Equal(t, "user", result[0].Name)
}

func newTestDragonfly(replicas int32) *resourcesv1.Dragonfly {
	return &resourcesv1.Dragonfly{
		TypeMeta: metav1.TypeMeta{
			APIVersion: "dragonflydb.io/v1alpha1",
			Kind:       "Dragonfly",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:      "test-df",
			Namespace: "default",
			UID:       types.UID("test-uid"),
		},
		Spec: resourcesv1.DragonflySpec{
			Replicas: replicas,
		},
	}
}

func TestGenerateDragonflyResources_ReadinessGateDisabled(t *testing.T) {
	df := newTestDragonfly(2)
	df.Spec.EnableReplicationReadinessGate = false

	resources, err := GenerateDragonflyResources(df, "")
	require.NoError(t, err)

	for _, obj := range resources {
		if sts, ok := obj.(*appsv1.StatefulSet); ok {
			assert.Empty(t, sts.Spec.Template.Spec.ReadinessGates,
				"readiness gates should be empty when feature is disabled")
			return
		}
	}
	t.Fatal("StatefulSet not found in generated resources")
}

func TestGenerateDragonflyResources_ReadinessGateEnabled(t *testing.T) {
	df := newTestDragonfly(2)
	df.Spec.EnableReplicationReadinessGate = true

	resources, err := GenerateDragonflyResources(df, "")
	require.NoError(t, err)

	for _, obj := range resources {
		if sts, ok := obj.(*appsv1.StatefulSet); ok {
			require.Len(t, sts.Spec.Template.Spec.ReadinessGates, 1,
				"should have exactly one readiness gate when feature is enabled")
			assert.Equal(t,
				corev1.PodConditionType(ReplicationReadyConditionType),
				sts.Spec.Template.Spec.ReadinessGates[0].ConditionType,
			)
			return
		}
	}
	t.Fatal("StatefulSet not found in generated resources")
}

func findNetworkPolicy(objs []client.Object) *networkingv1.NetworkPolicy {
	for _, obj := range objs {
		if np, ok := obj.(*networkingv1.NetworkPolicy); ok {
			return np
		}
	}
	return nil
}

func TestGenerateDragonflyResources_NetworkPolicyDefault(t *testing.T) {
	df := &resourcesv1.Dragonfly{
		ObjectMeta: metav1.ObjectMeta{
			Name:      "test-df",
			Namespace: "default",
		},
		Spec: resourcesv1.DragonflySpec{
			Replicas: 1,
		},
	}

	objs, err := GenerateDragonflyResources(df, "")
	require.NoError(t, err)

	np := findNetworkPolicy(objs)
	require.NotNil(t, np, "NetworkPolicy should be generated by default")

	assert.Equal(t, "test-df", np.Name)
	assert.Equal(t, "default", np.Namespace)

	assert.Equal(t, map[string]string{
		DragonflyNameLabelKey:     "test-df",
		KubernetesPartOfLabelKey:  KubernetesPartOf,
		KubernetesAppNameLabelKey: KubernetesAppName,
	}, np.Spec.PodSelector.MatchLabels)

	require.Len(t, np.Spec.Ingress, 2)
	assert.Equal(t, []networkingv1.PolicyType{networkingv1.PolicyTypeIngress}, np.Spec.PolicyTypes)

	protocolTCP := corev1.ProtocolTCP

	clientRule := np.Spec.Ingress[0]
	assert.Len(t, clientRule.From, 0, "client port should be open to all")
	require.Len(t, clientRule.Ports, 1)
	assert.Equal(t, &protocolTCP, clientRule.Ports[0].Protocol)
	assert.Equal(t, intstr.FromInt32(DragonflyPort), *clientRule.Ports[0].Port)

	adminRule := np.Spec.Ingress[1]
	require.Len(t, adminRule.Ports, 1)
	assert.Equal(t, intstr.FromInt32(DragonflyAdminPort), *adminRule.Ports[0].Port)
	require.Len(t, adminRule.From, 2)

	operatorPeer := adminRule.From[0]
	assert.Equal(t, map[string]string{
		OperatorControlPlaneLabelKey: OperatorControlPlaneLabelValue,
	}, operatorPeer.PodSelector.MatchLabels)
	assert.NotNil(t, operatorPeer.NamespaceSelector, "operator peer should allow cross-namespace")

	peerPod := adminRule.From[1]
	assert.Equal(t, map[string]string{
		DragonflyNameLabelKey:     "test-df",
		KubernetesPartOfLabelKey:  KubernetesPartOf,
		KubernetesAppNameLabelKey: KubernetesAppName,
	}, peerPod.PodSelector.MatchLabels)
	assert.Nil(t, peerPod.NamespaceSelector, "peer pod should be same-namespace only")
}

func TestGenerateDragonflyResources_NetworkPolicyDisabled(t *testing.T) {
	disabled := false
	df := &resourcesv1.Dragonfly{
		ObjectMeta: metav1.ObjectMeta{
			Name:      "test-df",
			Namespace: "default",
		},
		Spec: resourcesv1.DragonflySpec{
			Replicas:             1,
			NetworkPolicyEnabled: &disabled,
		},
	}

	objs, err := GenerateDragonflyResources(df, "")
	require.NoError(t, err)

	np := findNetworkPolicy(objs)
	assert.Nil(t, np, "NetworkPolicy should not be generated when disabled")
}

func TestGenerateDragonflyResources_NetworkPolicyWithMemcached(t *testing.T) {
	df := &resourcesv1.Dragonfly{
		ObjectMeta: metav1.ObjectMeta{
			Name:      "test-df",
			Namespace: "default",
		},
		Spec: resourcesv1.DragonflySpec{
			Replicas:      1,
			MemcachedPort: 11211,
		},
	}

	objs, err := GenerateDragonflyResources(df, "")
	require.NoError(t, err)

	np := findNetworkPolicy(objs)
	require.NotNil(t, np)

	require.Len(t, np.Spec.Ingress, 3, "should have client, admin, and memcached rules")

	protocolTCP := corev1.ProtocolTCP
	memcachedRule := np.Spec.Ingress[2]
	assert.Len(t, memcachedRule.From, 0, "memcached port should be open to all")
	require.Len(t, memcachedRule.Ports, 1)
	assert.Equal(t, &protocolTCP, memcachedRule.Ports[0].Protocol)
	assert.Equal(t, intstr.FromInt32(11211), *memcachedRule.Ports[0].Port)
}


func findStatefulSet(objs []client.Object) *appsv1.StatefulSet {
	for _, obj := range objs {
		if sts, ok := obj.(*appsv1.StatefulSet); ok {
			return sts
		}
	}
	return nil
}

func findConfigMap(objs []client.Object, name string) *corev1.ConfigMap {
	for _, obj := range objs {
		if cm, ok := obj.(*corev1.ConfigMap); ok && cm.Name == name {
			return cm
		}
	}
	return nil
}

func TestProbeConfigMaps_Generated(t *testing.T) {
	df := newTestDragonfly(1)
	objs, err := GenerateDragonflyResources(df, "")
	require.NoError(t, err)

	liveness := findConfigMap(objs, "test-df-liveness-probe")
	require.NotNil(t, liveness, "liveness-probe ConfigMap should be generated")
	assert.Contains(t, liveness.Data, "liveness-check.sh")
	assert.Contains(t, liveness.Data["liveness-check.sh"], "redis-cli")

	readiness := findConfigMap(objs, "test-df-readiness-probe")
	require.NotNil(t, readiness, "readiness-probe ConfigMap should be generated")
	assert.Contains(t, readiness.Data, "readiness-check.sh")
	assert.Contains(t, readiness.Data["readiness-check.sh"], "redis-cli")

	startup := findConfigMap(objs, "test-df-startup-probe")
	require.NotNil(t, startup, "startup-probe ConfigMap should be generated")
	assert.Contains(t, startup.Data, "startup-check.sh")
	assert.Contains(t, startup.Data["startup-check.sh"], "redis-cli")
}


func TestProbeVolumesAndMounts_Default(t *testing.T) {
	df := newTestDragonfly(1)
	objs, err := GenerateDragonflyResources(df, "")
	require.NoError(t, err)

	sts := findStatefulSet(objs)
	require.NotNil(t, sts)

	volumes := sts.Spec.Template.Spec.Volumes
	volumeNames := make(map[string]string) // name -> configmap name
	for _, v := range volumes {
		if v.ConfigMap != nil {
			volumeNames[v.Name] = v.ConfigMap.Name
		}
	}
	assert.Equal(t, "test-df-liveness-probe", volumeNames[LivenessProbeVolumeName])
	assert.Equal(t, "test-df-readiness-probe", volumeNames[ReadinessProbeVolumeName])
	assert.Equal(t, "test-df-startup-probe", volumeNames[StartupProbeVolumeName])

	mounts := sts.Spec.Template.Spec.Containers[0].VolumeMounts
	mountPaths := make(map[string]corev1.VolumeMount)
	for _, m := range mounts {
		mountPaths[m.Name] = m
	}
	assert.Equal(t, ProbeMountPath+"/"+LivenessScriptKey, mountPaths[LivenessProbeVolumeName].MountPath)
	assert.Equal(t, LivenessScriptKey, mountPaths[LivenessProbeVolumeName].SubPath)
	assert.Equal(t, ProbeMountPath+"/"+ReadinessScriptKey, mountPaths[ReadinessProbeVolumeName].MountPath)
	assert.Equal(t, ReadinessScriptKey, mountPaths[ReadinessProbeVolumeName].SubPath)
	assert.Equal(t, ProbeMountPath+"/"+StartupScriptKey, mountPaths[StartupProbeVolumeName].MountPath)
	assert.Equal(t, StartupScriptKey, mountPaths[StartupProbeVolumeName].SubPath)
}

func TestProbes_PointToMountedScripts(t *testing.T) {
	df := newTestDragonfly(1)
	objs, err := GenerateDragonflyResources(df, "")
	require.NoError(t, err)

	sts := findStatefulSet(objs)
	require.NotNil(t, sts)
	c := sts.Spec.Template.Spec.Containers[0]

	require.NotNil(t, c.LivenessProbe)
	assert.Equal(t, []string{"/bin/sh", ProbeMountPath + "/" + LivenessScriptKey}, c.LivenessProbe.Exec.Command)

	require.NotNil(t, c.ReadinessProbe)
	assert.Equal(t, []string{"/bin/sh", ProbeMountPath + "/" + ReadinessScriptKey}, c.ReadinessProbe.Exec.Command)

	require.NotNil(t, c.StartupProbe)
	assert.Equal(t, []string{"/bin/sh", ProbeMountPath + "/" + StartupScriptKey}, c.StartupProbe.Exec.Command)
	assert.Equal(t, int32(60), c.StartupProbe.FailureThreshold)
}

func TestProbeVolumes_CustomConfigMapOverride(t *testing.T) {
	df := newTestDragonfly(1)
	df.Spec.CustomReadinessProbeConfigMap = &corev1.LocalObjectReference{Name: "my-readiness-check"}

	objs, err := GenerateDragonflyResources(df, "")
	require.NoError(t, err)

	sts := findStatefulSet(objs)
	require.NotNil(t, sts)

	volumes := sts.Spec.Template.Spec.Volumes
	for _, v := range volumes {
		if v.Name == ReadinessProbeVolumeName {
			require.NotNil(t, v.ConfigMap)
			assert.Equal(t, "my-readiness-check", v.ConfigMap.Name,
				"custom ConfigMap should be mounted for readiness probe")
			return
		}
	}
	t.Fatal("readiness-probe volume not found")
}

func TestProbeVolumes_CustomLivenessConfigMapOverride(t *testing.T) {
	df := newTestDragonfly(1)
	df.Spec.CustomLivenessProbeConfigMap = &corev1.LocalObjectReference{Name: "my-liveness-check"}

	objs, err := GenerateDragonflyResources(df, "")
	require.NoError(t, err)

	sts := findStatefulSet(objs)
	require.NotNil(t, sts)

	for _, v := range sts.Spec.Template.Spec.Volumes {
		if v.Name == LivenessProbeVolumeName {
			require.NotNil(t, v.ConfigMap)
			assert.Equal(t, "my-liveness-check", v.ConfigMap.Name)
			return
		}
	}
	t.Fatal("liveness-probe volume not found")
}

func TestProbeVolumes_CustomStartupConfigMapOverride(t *testing.T) {
	df := newTestDragonfly(1)
	df.Spec.CustomStartupProbeConfigMap = &corev1.LocalObjectReference{Name: "my-startup-check"}

	objs, err := GenerateDragonflyResources(df, "")
	require.NoError(t, err)

	sts := findStatefulSet(objs)
	require.NotNil(t, sts)

	for _, v := range sts.Spec.Template.Spec.Volumes {
		if v.Name == StartupProbeVolumeName {
			require.NotNil(t, v.ConfigMap)
			assert.Equal(t, "my-startup-check", v.ConfigMap.Name)
			return
		}
	}
	t.Fatal("startup-probe volume not found")
}
