apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: dragonfly-sample
  labels:
    group: dragonfly
    app: dragonfly-sample
spec:
  selector:
    matchLabels:
      app: dragonfly-sample
  podMetricsEndpoints:
  - port: admin
