apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
spec:
  selector:
    prometheus: prometheus
  type: ClusterIP
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web

