name: ci

on:
  # push:
  # branches: [ main ]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-operator:
    runs-on: ubuntu-latest
    env:
      IMG: ghcr.io/dragonflydb/operator:${{ github.sha }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-go@v3

      - name: Build Operator
        run: |
          make build

      - name: Docker Build
        run: |
          make docker-build

      - uses: helm/kind-action@v1.5.0

      - name: Run tests
        timeout-minutes: 6
        run: |
          make docker-kind-load
          make deploy
          make test

