name: CI

on:
  # push:
  # branches: [ main ]
  pull_request:
    branches: [main]
  workflow_dispatch:
  push:
    branches: [main]
    tags:
      - v*

jobs:
  build-operator:
    runs-on: ubuntu-latest
    env:
      IMG: ghcr.io/dragonflydb/operator:${{ github.sha }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Docker Build
        run: |
          make docker-build

      - uses: helm/kind-action@v1.5.0
        with:
          cluster_name: kind

      - name: Run tests
        timeout-minutes: 10
        run: |
          make docker-kind-load
          make deploy
          make test

      - name: Publish image into GHCR
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/dragonflydb/operator:${{ github.ref_name }}
        env:
          DOCKER_BUILDKIT: 1
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
